ethereum_rpc = "https://eth.llamarpc.com"
drosera_rpc = "https://relay.mainnet.drosera.io"
eth_chain_id = 1
drosera_address = "0x0c4f7e9684a11805Fc5406989F5124bFC2AD0D84"

[traps]
[traps.void_catalyst]
path = "out/VoidCatalystTrap.sol/VoidCatalystTrap.json"
response_contract = "0xB400bC781d57aa26592940b31f5967bA015a7df6"
response_function = "executeIgnition(uint256)"
cooldown_period_blocks = 5
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 1 
private_trap = true
whitelist = ["0xcF75BeA7A11Eb0A764dC85DEf2F36c3ed826aE59"]
address = "0x1521a1C75cdeDC18d325ef430505d326A0646354"
